//home_icon_01.js 开始顶部1-------------------------------------------------------------------
document.getElementById("homeicon01").innerHTML="<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr><td><div align=\"center\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"165\" height=\"60\"><param name=movie value=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_guangda.swf\"><param name=quality value=high><embed src=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_guangda.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"165\" height=\"60\"><\/embed><\/object><\/div><\/td><\/tr><\/table>";
// home_icon_01.js 结束--------------------------------------------------------

//home_icon_02.js开始顶部2 -------------------------------------------------------------------
a = 2 // a=numbers of banners
var slump = Math.random();
var talet = Math.round(slump * (a-1))+1;
if (talet=="1"){
document.getElementById("homeicon02").innerHTML="<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr><td><div align=\"center\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"625\" height=\"60\"><param name=movie value=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_wanggou_62560.swf\"><param name=quality value=high><embed src=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_wanggou_62560.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"625\" height=\"60\"><\/embed><\/object><\/div><\/td><\/tr><\/table>";
}
else 
{
document.getElementById("homeicon02").innerHTML="<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr><td><div align=\"center\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"625\" height=\"60\"><param name=movie value=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_wly_62560.swf\"><param name=quality value=high><embed src=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_wly_62560.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"625\" height=\"60\"><\/embed><\/object><\/div><\/td><\/tr><\/table>";
}
//home_icon_02.js结束 ------------------------------------------------------------------------------

//home_icon_03.js开始顶部3 -------------------------------------------------------------------
document.getElementById("homeicon03").innerHTML="<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr><td><div align=\"center\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"165\" height=\"60\"><param name=movie value=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_guojiadianwan.swf\"><param name=quality value=high><embed src=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_guojiadianwan.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"165\" height=\"60\"><\/embed><\/object><\/div><\/td><\/tr><\/table>";
//home_icon_03.js结束 -------------------------------------------------------------------

//home_an_16570_01.js开始 -------------------------------------------------------------------
document.getElementById("homean1657001").innerHTML="<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr><td><div align=\"center\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"165\" height=\"70\"><param name=movie value=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_fujian.swf\"><param name=quality value=high><embed src=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_fujian.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"165\" height=\"70\"><\/embed><\/object><\/div><\/td><\/tr><\/table>";
//home_an_16570_01.js结束 -------------------------------------------------------------------

//home_an_16570_02.js开始 -------------------------------------------------------------------
document.getElementById("homean1657002").innerHTML="<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr><td><div align=\"center\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"165\" height=\"70\"><param name=movie value=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_20100122b.swf\"><param name=quality value=high><embed src=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_20100122b.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"165\" height=\"70\"><\/embed><\/object><\/div><\/td><\/tr><\/table>";
//home_an_16570_02.js结束 -------------------------------------------------------------------

//home_300180.js开始 -------------------------------------------------------------------
document.getElementById("home300180").innerHTML="<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr><td><div align=\"center\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"300\" height=\"180\"><param name=movie value=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_20100122a.swf\"><param name=quality value=high><embed src=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_20100122a.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"300\" height=\"180\"><\/embed><\/object><\/div><\/td><\/tr><\/table>";
//home_300180.js结束 -------------------------------------------------------------------

//hp_tl_01.js开始-----------------------------------------------------------------
document.getElementById("hptl01").innerHTML="<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr><td><div align=\"center\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"760\" height=\"80\"><param name=movie value=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_wanggou_76080.swf\"><param name=quality value=high><embed src=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_wanggou_76080.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"760\" height=\"80\"><\/embed><\/object><\/div><\/td><\/tr><\/table>";
//hp_tl_01.js结束-----------------------------------------------------------------

//hp_an_01.js开始-----------------------------------------------------------------
document.getElementById("hpan01").innerHTML="<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"><tr><td><div align=\"center\"><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"200\" height=\"80\"><param name=movie value=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_zhejiangyiwu.swf\"><param name=quality value=high><embed src=\"\/page_load_test\/tp5\/xinhuanet.com\/imgs.xinhuanet.com\/ad\/ad_zhejiangyiwu.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"200\" height=\"80\"><\/embed><\/object><\/div><\/td><\/tr><\/table>";
//hp_an_01.js结束-----------------------------------------------------------------