function fGetCookie(name){var cookieValue="";var search=name+"=";if(document.cookie.length>0){offset=document.cookie.indexOf(search);if(offset!=-1){offset+=search.length;end=document.cookie.indexOf(";",offset);if(end==-1)end=document.cookie.length;cookieValue=unescape(document.cookie.substring(offset,end));}}
return cookieValue;}
function fSetCookie(name,value,time,tdomain){var expire="";if(tdomain){var domain="; domain=56.com; path=/";}
else{var domain="";}
if(time!=""){expire=new Date((new Date()).getTime()+time);expire="; expires="+expire.toGMTString();}
document.cookie=name+"="+escape(value)+expire+domain;}
function fJ_get(name){var get=location.search||location.hash;var start=get.indexOf(name+'=');if(start==-1)return'';var len=start+name.length+1;var end=get.indexOf('&',len);if(end==-1)end=get.length;return unescape(get.substring(len,end));}
function randomChar(m){var x="0123456789poiuytrewqasdfghjklmnbvcxzQWERTYUIOPLKJHGFDSAZXCVBNM";var tmp="";for(var i=0;i<m;i++){tmp+=x.charAt(Math.ceil(Math.random()*100000000)%x.length);}
return tmp;}
function inc(url,id){a=document.createElement('script');if(id)a.setAttribute("id","script_"+id);a.setAttribute("charset","gb2312");a.type='text/javascript';a.src=url;document.getElementsByTagName('HEAD')[0].appendChild(a);}
function hasRef(s){return document.referrer.indexOf(s)>-1;}
var expireDate=new Date();var hours=expireDate.getHours();var minutes=expireDate.getMinutes();var seconds=expireDate.getSeconds();var agt=navigator.userAgent.toLowerCase();var isalexa=agt.indexOf("alexa")>-1?1:0;var data='&r='+escape(document.referrer)+'&l='+escape(location.href);var wole_all_s=fGetCookie("wl_all_s");var wole_site_s=fGetCookie("wl_"+webid+"_s");var isunion=fGetCookie("u_cid")?"1":"0";var unioninfo=fGetCookie("u_info");var member_id=fGetCookie("member_id");var geoip=fGetCookie("geoip");var c_h=fGetCookie("c_h")?"y":"";var unioninfoArray=unioninfo.split("--");var unionid=unioninfoArray[0]?unioninfoArray[0]:'';var siteid=unioninfoArray[1]?unioninfoArray[1]:'';var all_ind_user=wole_all_s=="y"?"0":"1";var site_ind_user=wole_site_s=="y"?"0":"1";var lefttime=1000*(86400-hours*3600-minutes*60-seconds);if(isunion==0&&(hasRef("baidu.com")||hasRef(".9991.")||hasRef(".2345.")||hasRef("hao123.com")||hasRef("video.56.com")||hasRef("so.56.com")||hasRef("hao.qq.com"))){isunion="1";if(hasRef("hao123.com")){unionid="hao123";u_info="hao123--0";}else if(hasRef(".9991.")||hasRef(".2345.")){unionid="9991";u_info="9991--0";}else if(hasRef("baidu.com")){unionid="baidu";u_info="baidu--1";}else if(hasRef("video.56.com")){unionid="video56";u_info="video56--1";}else if(hasRef("so.56.com")){unionid="so56";u_info="so56--1";}else if(hasRef("hao.qq.com")){unionid="haoqq";u_info="haoqq--1";}
fSetCookie("u_cid","1","",1);fSetCookie("u_info",u_info,"",1);}
if(fJ_get('unid')){isunion="1";unionid=fJ_get('unid');siteid=fJ_get('usid');u_info=unionid+"--"+siteid;fSetCookie("u_cid",isunion,"",1);fSetCookie("u_info",u_info,"",1);}
var cp=0;if(typeof(oFlv)!="undefined"&&typeof(oFlv.o)!="undefined"&&typeof(oFlv.o.cid2)!="undefined"&&oFlv.o.cid2!=0){cp=1;}
inc('stat.gif');fSetCookie("wl_all_s","y",lefttime,1);fSetCookie("wl_"+webid+"_s","y",lefttime,1);if(member_id.indexOf('guest')>-1){fSetCookie("member_id","",lefttime,1);}
if(c_h==""&&location.href.match(/http:\/\/www.56.com\/\w\d\d\//)&&(document.referrer==''||document.referrer.indexOf('.56.com')<0)){fSetCookie("c_h","y",30000,1);inc('http://stat2.corp.56.com/check/?'+location.href);}
try{top.location.host}catch(e){void("<img src=http://acs.56.com/redirect/click/1531/http://  border=0 width=1 height=1>");}
try{var outframe=Array("video.baidu.com","www.video.baidu.com","www.baidu.com","search.baidu.com");var adr=document.referrer;var a_ua=navigator.userAgent.toLowerCase();var a_isFF=a_ua.indexOf('firefox')>=0;var a_isIE=(a_ua.indexOf('msie')>=0&&a_ua.indexOf('opera')<0);var a_isSFR=a_ua.indexOf('safari')>=0;if(parent&&((a_isIE&&parent!=document)||((a_isFF||a_isSFR)&&parent!=window))&&adr!=""&&adr!=self.location&&!adr.match(/\:\/\/[a-z0-9\-\.]+\.56\.com/)){var is_frame=false;for(var i=0;i<outframe.length;i++){if(adr.match(/\:\/\/([\w\.\-\d]+)\//g)=="://"+outframe[i]+"/"){is_frame=true;break;}}
if(is_frame==false)parent.location=self.location;}}catch(e){}
if(location.href.indexOf('http://so.56.com/index?')>-1){var ad_56com_cid=31;ad_56com_height=1;var ad_56com_width=1;}
(function(){var lst=fGetCookie("lst");if(lst){setInterval("inc('http://stat.56.com/php/lst.php')",600000);return;}else{if(member_id&&member_id.indexOf("guest")!=0){void("<img style='display:none;' src='http://stat.56.com/php/lst.php' />");setInterval("inc('http://stat.56.com/php/lst.php')",600000);}}})();if(document.getElementById("Search_input")&&(new Date).getDate()==15&&((new Date).getMonth())+1==8){}
if(window.location.href=="httpdisabled://www.56.com/"||window.location.href.indexOf("news.56.com")>-1){}else{if(document.referrer&&document.referrer.indexOf("video.baidu.com")>0&&location==parent.location){void('<script>ad_56com_cid=93; ad_56com_width=0; ad_56com_height=0;</scr'+'ipt>');void('<script src="httpdisabled://acs.56.com/ac/ac_93.js" charset="gb2312"></scr'+'ipt>');}else if(document.referrer&&document.referrer.indexOf("www.baidu.com")>0&&location==parent.location){if(window.location.href.indexOf("httpdisabled://www.56.com/u")>-1||window.location.href.indexOf("play_album-aid")>-1){void('<script>ad_56com_cid=93; ad_56com_width=0; ad_56com_height=0;</scr'+'ipt>');void('<script src="httpdisabled://acs.56.com/ac/ac_93.js" charset="gb2312"></scr'+'ipt>');}}else if(document.referrer&&document.referrer.indexOf("sogou.com")>0&&location==parent.location){var ad_56com_cid=16;ad_56com_height=1;var ad_56com_width=1;void("<script src=http://acs.56.com/ac/ac_16.js></s"+"cript>");}}
function check_google(){if(typeof(google_in_use)!=='undefined'&&google_in_use==1&&document.getElementById('rAD34_300x250_show')&&document.getElementById('rAD2_420x60')){document.getElementById('rAD2_420x60').innerHTML=document.getElementById('rAD34_300x250_hide').innerHTML;}}
setTimeout("check_google()",2000);
