
var G={};G={$:function(id){return document.getElementById(id);},trim:function(str){return str.replace(/^\s+|\s+$/g,'');},time:function(){return new Date().getTime();},goiframe:function(url){window.frames.add_favorite.location=url;},setcookie:function(cookieName,cookieValue,seconds,path,domain,secure){if(domain==undefined||domain==null||domain==""){var domain=".56.com";}
var expires=new Date();expires.setTime(expires.getTime()+seconds*1000);document.cookie=encodeURIComponent(cookieName)+'='+encodeURIComponent(cookieValue)
+(expires?'; expires='+expires.toGMTString():'')
+(path?'; path='+path:'/')
+(domain?'; domain='+domain:'')
+(secure?'; secure':'');},getcookie:function(name){var cookie_start=document.cookie.indexOf(name);var cookie_end=document.cookie.indexOf(";",cookie_start);var str='';try{str=cookie_start==-1?'':decodeURIComponent(document.cookie.substring(cookie_start+name.length+1,(cookie_end>cookie_start?cookie_end:document.cookie.length)));}catch(e){};return str;},importJs:function(url,func){var head=document.getElementsByTagName("head")[0];var script=document.createElement("script");script.type="text/javascript";script.onload=script.onreadystatechange=function(){if(!script.readyState||"loaded"==script.readyState||"complete"==script.readyState){eval(func+'()');script.onload=script.onreadystatechange=null;script.parentNode.removeChild(script)}};script.src=url;head.appendChild(script);}};var W={};var xmlhttp=null;var jsonobj;var wConfig={};W={changeCity:function(name){var len=cityLib.length;var countylen=countyLib.length;var i=-1,k=-1;while(++i<len){if(cityLib[i][0]==name){var obj=cityLib[i][1];var tlen=obj.length;var result=['<select id="citysel" onchange="W.changeCounty(this.options[this.options.selectedIndex].value)">'];for(var j=0;j<tlen;j++){result.push('<option value="'+obj[j]+'">'+obj[j]+'</option>');}
result.push('</select>');document.getElementById("selectCity").innerHTML=result.join('');while(++k<countylen){if(countyLib[k][0]==obj[0]){var cobj=countyLib[k][1];var ctlen=cobj.length;var cresult=['<select id="xiansel">'];for(var q=0;q<ctlen;q++){cresult.push('<option value="'+cobj[q]+'">'+cobj[q]+'</option>');}
cresult.push('</select>');document.getElementById("selectCounty").innerHTML=cresult.join('');}}}}},changeCounty:function(name){var len=countyLib.length;var i=-1;while(++i<len){if(countyLib[i][0]==name){var obj=countyLib[i][1];var tlen=obj.length;var result=['<select id="xiansel">'];for(var j=0;j<tlen;j++){result.push('<option value="'+obj[j]+'">'+obj[j]+'</option>');}
result.push('</select>');document.getElementById("selectCounty").innerHTML=result.join('');}}},gotoweatherlink:function(){setStat('linkweather');if(this.weatherlink!=''){window.open(this.weatherlink,'56网天气预告');}},isrundefault:0,weatherlink:'',setweather:function(jsonobj){var tpl;var ele=document.createElement("div");if(jsonobj.weatherinfo.city==undefined||jsonobj.weatherinfo.city==''){if(this.isrundefault==0){this.setdefault();this.isrundefault=1;}else{tpl='';G.$("weather_info").innerHTML=tpl;}}else{this.weatherlink=jsonobj.weatherinfo.link;tpl='<a href="javascript:void(0);" onclick="W.gotoweatherlink();" title="点击查看详细天气情况">&nbsp;<strong>'+jsonobj.weatherinfo.weather+'</strong> '+jsonobj.weatherinfo.temp.replace('~','℃～')+'℃'+'</a>';G.$("weather_info").innerHTML=tpl;G.$('locity').innerHTML='<a href="javascript:void(0);" class="drop_menu_title" id="set_area" onclick="W.openselected();">'+(G.getcookie("xiansel")?G.getcookie("xiansel"):jsonobj.weatherinfo.city)+'<em class="arrow">V</em></a>';}
G.$("ydaSubmit").onclick=function(e){var prov=G.$("provincesel").value;if(prov==''||prov==undefined){return;}
if(G.$("citysel").value==null){return;}
var city=G.$("citysel").value;var xian=G.$("xiansel").value;if(!prov||!city||!xian){alert("请选择相应的城市");}else{G.setcookie("citysel",city,2592000);G.setcookie("cityname",xian,2592000);W.getWeather(xian);W.closeselected();}
if(e&&e.preventDefault){e.preventDefault();}else{window.event.returnValue=false;}};},closeselected:function(){document.getElementById('dropMenu1').className='drop_menu';G.$("locList").style.display="none";},openselected:function(){setStat('setweather');W.setSelected();W.controlT();},isselected:0,setSelected:function(){if(this.isselected==0){var len=cityLib.length;var result=['<select id="provincesel" onchange="W.changeCity(this.options[this.options.selectedIndex].value)"><option value="">选择省</option>'];for(var i=0;i<len;i++){result.push('<option value="'+cityLib[i][0]+'">'+cityLib[i][0]+'</option>');}
result.push('</select>');G.$("selectProvince").innerHTML=result.join('');this.isselected=1;}},controlT:function(){if(document.getElementById('dropMenu1').className=='drop_menu'){document.getElementById('dropMenu1').className='drop_menu_active';G.$("locList").style.display="";}else{document.getElementById('dropMenu1').className='drop_menu';G.$("locList").style.display="none";}},checkCity:function(){if(typeof('countyLib')=='undefined'||typeof('cityLib')=='undefined'){G.importJs(wConfig.dataCity,'W.setSelected');}},getWeather:function(geturl){var url=wConfig.dataUrl+encodeURI(geturl);jLoader(url);},updatelocal:function(){var len=countyLib.length;var fflag=1;for(var i=0;i<len;i++){if(countyLib[i][0]==wConfig.cityName){G.setcookie("cityname",wConfig.cityName,2592000);W.getWeather(wConfig.cityName);fflag=2;break;}}
if(fflag==1){wConfig.cityName=wConfig.defaultCity;G.setcookie("cityname",wConfig.cityName,2592000);W.getWeather(wConfig.cityName);}},setdefault:function(){if(!wConfig.cityName){}else{this.checkCity();this.updatelocal();}},init:function(){wConfig.cityName=G.getcookie("cityname");if(""==wConfig.cityName||('北京'==wConfig.cityName&&''==G.getcookie("isbeijiang"))){if('北京'==wConfig.cityName){G.setcookie("isbeijiang",'y',2592000);}
this.setdefault();}else{W.getWeather(wConfig.cityName);}},getutf8geoip:function(data){wConfig.cityName=this.changeName(data['geoip']);G.setcookie("cityname",wConfig.cityName,2592000);W.getWeather(wConfig.cityName);},changeName:function(name){return name.substring(name.lastIndexOf('省')+1,name.lastIndexOf('市'));}};W.init();
