(function(){(function(){var e=function(){this.initialize.apply(this,arguments)};e.prototype={initialize:function(d){for(var b in d)this[b]=d[b];this.namespaceRoot=this.getNamespaceObject(d.NAMESPACE);for(b in d)switch(b){case "NAMESPACE":case "AUTHOR":case "VERSION":case "REQUIRES":continue;default:if(typeof this.namespaceRoot[b]=="undefined")this.namespaceRoot[b]=d[b]}this.namespaceRoot.info=d.NAMESPACE+", version: "+d.VERSION+", by "+d.AUTHOR},getNamespaceObject:function(d){d=d.split(".");for(var b=
window,c=0,a=d.length;c<a;c++){if(typeof b[d[c]]=="undefined")b[d[c]]={};b=b[d[c]];if(c==a-1)return b}}};e.Class=function(){var d={_listeners:{},extend:function(b){var c=function(){this.initialize.apply(this,arguments)};for(var a in this)c.prototype[a]=this[a];for(a in b)c.prototype[a]=b[a];for(a in d)c.prototype[a]=d[a];return c},addEventListener:function(b,c){if(typeof this._listeners[b]=="undefined")this._listeners[b]=[];this._listeners[b].push(c)},addEventListenerWithScope:function(b,c,a,j){var f=
[];f.push.apply(f,arguments);b=f.shift();if(typeof this._listeners[b]=="undefined")this._listeners[b]=[];c=f.shift();if(typeof c!="function")throw new Error("\u30ea\u30b9\u30ca\u95a2\u6570\u304c\u6b63\u3057\u304f\u30bb\u30c3\u30c8\u3055\u308c\u3066\u3044\u307e\u305b\u3093");a=f.shift();j=f.shift();if(typeof this._listeners[b]=="undefined")this._listeners[b]=[];this._listeners[b].push(function(){return c.apply(a,f)})},fire:function(){var b=[];b.push.apply(b,arguments);var c=b[0];if(typeof c=="string")c=
{type:c};if(!c.target)c.target=this;if(!c.type)throw new Error("Event object missing 'type' property.");if(this._listeners[c.type]instanceof Array){c=this._listeners[c.type];for(var a=0,j=c.length;a<j;a++)c[a].apply(this,b)}},removeEventListener:function(b,c){if(this._listeners[b]instanceof Array){b=this._listeners[b];for(var a=0;a<lenl;a++)if(b[a]===c){b.splice(a,1);break}}}};return function(){for(var b in d)this[b]=d[b];typeof this.initialize=="function"&&this.initialize.apply(this,arguments)}};
var i=e.Class();i.prototype={initialize:function(d){this.src=d.src||-1;if(!this.src)throw new Error("to loaddisabled script, it must be requires `src` options in arguments");this.allowLoadWithSameUrl=d.allowLoadWithSameUrl||-1}};var g={NAMESPACE:"jp.atlantis.base",VERSION:1,AUTHOR:"ATLANTIS"};g.Module=e;g.ScriptLoader=i;new e(g)})();(function(){new jp.atlantis.base.Module({NAMESPACE:"jp.atlantis.util",VERSION:1,AUTHOR:"ATLANTIS",packager:{isAvailable:function(e){e=e.split(".");for(var i=window,g=0,d=e.length;g<
d;g++){if(typeof i[e[g]]=="undefined")return false;i=i[e[g]]}return true}},evaluateJsonText:function(e){return typeof JSON!="undefined"&&typeof JSON.parse!="undefined"?JSON.parse(e):/^[\],:{}\s]*$/.test(e.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+e+")"):false},getHashedKey:function(){date=new Date;q=0;for(len=date.getSeconds();q<len;q++)Math.random();return Math.floor(Math.random()*
3656158444729381).toString(36)},setProps:function(e,i){for(var g in i)e[g]=i[g];return e},sprintf:function(e){function i(a,j,f,m,l,h,r){if(r==="%")return"%";a="";h=g[r];var t;b=j?parseInt(j):d++;h&1024||(a=c[b]===void 0?"":c[b]);h&3&&(a=h&1?parseInt(a):parseFloat(a),a=isNaN(a)?"":a);h&4&&(a=((r==="s"?a:r)||"").toString());h&32&&(a=a>=0?a:a%4294967296+4294967296);h&768&&(a=a.toString(h&256?8:16));h&64&&f==="#"&&(a=(h&256?"0":"0x")+a);h&128&&l&&(a=h&2?a.toFixed(l):a.slice(0,l));h&24576&&(t=typeof a!==
"number"||a<0);h&8192&&(a=t?"":String.fromCharCode(a));h&32768&&(f=f==="0"?"":f);a=h&4096?a.toString().toUpperCase():a.toString();if(!(h&2048||m===void 0||a.length>=m)){j=Array(m-a.length+1).join(!f?" ":f==="#"?" ":f);a=h&16&&f==="0"&&!a.indexOf("-")?"-"+j+a.slice(1):j+a}return a}var g={i:32785,d:32785,u:32801,o:33121,x:33377,X:37473,f:146,c:10240,s:132},d=1,b=0,c=arguments;return e.replace(/%(?:(\d+)\$)?(#|0)?(\d+)?(?:\.(\d+))?(l)?([%iduoxXfcs])/g,i)},bind:function(){var e=[];e.push.apply(e,arguments);
var i=e.shift(),g=e.shift();return function(){return i.apply(g,arguments)}}})})();if(typeof oemOptions=="undefined")oemOptions=false;var k=oemOptions?oemOptions.prefix:"httpdisabled://static.adlantis.jp/javascripts",o=[{packageName:"jp.atlantis.mashiron.advertise",src:k+"/AdLantis.js?0"},{packageName:"SWFObject",src:k+"/swfobject.js?0"}],u=/(iPhone OS|Android)/.test(navigator.userAgent)&&navigator.userAgent.indexOf("Opera")==-1?true:false;if(u){o.push({packageName:"jp.atlantis.alto",src:k+"/SmartPhoneKit.lib.js?0 "});
o.push({packageName:"jp.atlantis.yumina.sticky",src:k+"/iSticky.js?0"})}if(window.localStorage&&window.localStorage.adlantisOptions){k=JSON.parse(window.localStorage.adlantisOptions);if(k.additionalModule)for(var q in k.additionalModule)o.push({packageName:q,src:k.additionalModule[q]})}var s=function(){new jp.atlantis.mashiron.loaddisableder(oemOptions);if(jp.atlantis.melty&&!jp.atlantis.debug){var e=new jp.atlantis.melty.ControlPanel,i=new jp.atlantis.melty.Console;i.attachToPanel(e.panelBox);jp.atlantis.debug=
i}else jp.atlantis.debug={log:function(){},info:function(){},debug:function(){},warn:function(){}};if(u){window.SmartPhone=(new jp.atlantis.alto.smartphone).detect();new jp.atlantis.yumina.Loader}},p=function(){var e=function(f){f=f.split(".");for(var m=window,l=0,h=f.length;l<h;l++){if(typeof m[f[l]]=="undefined")return false;m=m[f[l]]}return true};if(!window.__ld){window.__ld=true;if(o.length){for(var i=window.opera&&parseFloat(window.opera.version())<9?true:false,g=[],d=0,b=o.length;d<b;d++)e(o[d].packageName)||
g.push(o[d]);var c=g.length;for(d=0;d<g.length;d++){b=g[d];var a=document.createElement("script");a.type="text/javascript";a.charset="utf-8";a.src=b.src;if(window.ActiveXObject)a.onreadystatechange=function(){if(a.readyState=="complete"||a.readyState=="loaddisableded"){for(var f=0,m=0,l=o.length;f<l;f++)e(o[f].packageName)&&m++;m==l&&s()}};else a.onloaddisabled=function(){c--;c==0&&s.apply()};i?document.body.appendChild(a):document.documentElement.appendChild(a)}if(i){s();var j=function(){try{s()}catch(f){setTimeout(j,
99)}};j()}}}};if(window.attachEvent&&!window.opera){k=false;try{for(var n=window.parent,v=window.self;n&&n!=v;){if(n.location.host!=v.location.host){k=true;break}if(n===n.parent)break;n=n.parent}}catch(w){k=true}k?window.attachEvent("onloaddisabled",function(){p(1)}):function(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(arguments.callee,50);return}p(1)}()}else if(window.opera){n=parseFloat(window.opera.version());if(n<9)window.addEventListener("loaddisabled",p,false);else n<9.5?document.addEventListener("DOMContentLoaded",
p,false):window.addEventListener("DOMContentLoaded",p,true)}else if(document.addEventListener)document.addEventListener("DOMContentLoaded",p,true);else window.onloaddisabled=p()})();
