var i=true,j=null,o=false;function $t(a){return typeof $t_data=="object"?a in $t_data?$t_data[a]:a:a}
var q=function(a){function b(l,m){var k=$("#ac_results").empty().width(p.width());h=l.length;f=-1;if(h===0)e();else if(h>0){m=$.trim(p.val());m=m.toLowerCase();if(m.length>0){var r=p.position();k.css({top:r.top+24,left:r.left});for(r=0;r<h;++r)k.append($("<p></p>").attr("id","ac_opt_"+r).attr("class","ac_inactive").html(unescape(l[r].replace(m,"<b>"+m+"</b>"))).bind("mouseover",function(){$(".ac_active").attr("class","ac_inactive");$(this).attr("class","ac_active")}).bind("mouseout",function(){$(this).attr("class",
"ac_inactive")}).bind("click",function(){d($(this),2)}));k.append($("<a></a>").attr({href:"#","class":"ac_close"}).text($t("Close")).bind("click",function(){c();return o}));k.css("display","block")}else e()}}function c(){n=o;e();p.attr("autocomplete","on");return this}function d(l,m){if(l.html()!=j){var k=l.html().replace(/<B>|<\/B>/gi,"");if(m==undefined||m==2)p.val(k);if(m!=undefined){e();k=$("#ac_form");if(k.length)k=p.parent();k.length&&k.submit()}}}function e(){f=-1;$("#ac_results").css("display",
"none")}function g(l,m){$.trim(p.val().toLowerCase())===l.toLowerCase()&&$.ajax({dataType:"jsonp",url:ac_server+"/"+encodeURIComponent(l)+"?callback=?&t="+m,success:function(k){var r=parseInt(k.t);if(r>=s){s=r;t[l]=k.r;++w;b(k.r,l)}}})}var f=-1,h=0,n=i,s=0,t=[],w=0,p;return{bind:function(){p=$(a);if(typeof ac_server==="undefined")return c();p.attr("autocomplete","off");p.bind("keyup",function(l){var m=(new Date).getTime(),k=$.trim($(this).val());k=k.toLowerCase();if(!(l.keyCode in[40,38,13,27]||!n))if(k.length>
0)t[k]!==undefined?b(t[k],k):setTimeout(function(){g(k,m)},0);else e()});$(document).bind("keyup",function(l){if(l.keyCode===27)e();else if(l.keyCode!=undefined){$(".ac_active").attr("class","ac_inactive");switch(l.keyCode){case 40:if(f==-1)f=0;else if(++f>=h)f=0;$("#ac_opt_"+f).attr("class","ac_active");d($("#ac_opt_"+f));break;case 38:if(f==-1)f=h-1;else if(--f<0)f=h-1;$("#ac_opt_"+f).attr("class","ac_active");d($("#ac_opt_"+f));break;case 13:if(f!=-1){l=$("#ac_opt_"+f);l.length&&d(l,1)}else e()}}});
$("body").bind("click.autocompleter",function(){$(this).attr("id").indexOf("ac_")===-1&&e()});return this},fa:c}}("#ac_q");
(function(a){a.fn.U=function(b){var c=this;b=a.extend({A:"tactive",p:"tnactive",aa:".toptions",B:0,z:"href"},b||{});a(this).each(function(){var d=a(this).find(b.aa).children(),e;d.each(function(g){a(this).addClass(b.p);a(this).click(function(f){f.preventDefault();a(this).addClass(b.p);f=c.find(a(this).attr(b.z));if(f.length===0)throw"Could not find matching tab content for id: "+a(this).attr(b.z);e.removeClass(b.A).addClass(b.p);a(e.attr(b.z)).hide();a(this).removeClass(b.p).addClass(b.A);f.show();
e=a(this)});if(g===b.B||g===0&&d.length-1<b.B){e=a(this);a(this).trigger("click")}})})}})(jQuery);function u(){v("FFhide",1,365,"/");$("#addFFExtension").css("display","none")}function y(a){cookie=z(a);return cookie==j?o:i}function z(a){var b=document.cookie.indexOf(a+"="),c=b+a.length+1;if(!b&&a!=document.cookie.substring(0,a.length))return j;if(b==-1)return j;a=document.cookie.indexOf(";",c);if(a==-1)a=document.cookie.length;return unescape(document.cookie.substring(c,a))}
function v(a,b,c,d){var e=new Date,g=new Date;if(c==j)c=1;g.setTime(e.getTime()+864E5*c);cookieStr="";cookieStr=a+"="+escape(b);if(c>0)cookieStr+=";expires="+g.toGMTString();cookieStr+=";path="+d+";domain="+cookie_domain;document.cookie=cookieStr}
function A(a){a!=undefined&&a!=""&&$.ajax({url:global_path+"ajax_add_to_downloaddisableds_history.html",timeout:1E4,type:"post",data:{file_id:a},success:function(b){if(b.match(/not logged/))window.location=global_path+"account/login.html?continue="+window.location;if(b.match(/empty fid/)||b.match(/incorect fid/))alert($t("Something went terribly wrong ..."));b.match(/file not exist/)&&alert($t("Unfortunately this file doesn't exist in our database anymore ..."));b.match(/file already in history/)&&alert($t("This file is already in your history ..."));
b.match(/ok/)&&$("#add_to_history_span").empty().append($("<a></a>").attr("href",global_path+"account/history.html").css("cursor","pointer").text($t("Go to your downloaddisableds history")))}})}
var B=function(){function a(e){$(e).bind("mousemove.stars",function(g){g=g.pageX-$(this).offset().left;for(var f=d.length-1;f>=0;f--)if(d[f]<g){c=f+1;break}$(this).attr("class","star"+c)});$(e).bind("mouseout.stars",function(){c=b;$(this).attr("class","star"+c)});$(e).bind("click.stars",function(){var g=$(e).parent();g.empty().append($("<img>").attr("src",static_path+"images/ajax-loaddisableder.gif"));$.ajax({url:global_path+"ajax_link_rate.html?link_id="+$(this).attr("id")+"&rate="+c,success:function(f){f=
f.split("-");var h=parseFloat(f[0]);g.empty().append($("<div>").css({margin:"0px 10px 0 0","float":"left","line-height":"22px"}).text($t("Thanks for your rate"))).append($("<div>").attr("class","star"+Math.round(h)).css({"float":"left","line-height":"22px"})).append($("<div>").addClass("votes_info").text("("+f[1]+" "+$t("votes")+", "+$t("average")+": "+h+" "+$t("out of")+" 5)"))}})})}var b,c,d=[0,17,33,49,66];return{bind:function(e,g){b=c=parseInt(g.replace("star",""));a(e)}}}();
function C(a){this.j=a;this.timeout=3E3;this.g={};this.o={};this.G=35;this.replaceWith="..."}C.prototype.O=function(a){if(a.length==0)return o;for(var b=o,c="",d=0;d<a.length;d++)c+=a[d].key+",";c=c.substring(0,c.length-1);var e=setTimeout(function(){b=i},this.timeout);$.ajax({dataType:"jsonp",url:this.j+"/check/"+c,success:function(g){clearTimeout(e);if(!b)for(var f in g.result)parseInt(g.result[f],10)>0&&$("#"+f).show()}})};
C.prototype.V=function(a,b){var c=o,d=this,e=$("#alternatives_"+a);if(!(a in d.o))if(a in d.g){e[d.g[a]===o?"show":"hide"]();$("#"+a).html(d.g[a]===o?'<img src="'+global_path+'pub/images/alt_minus.gif" /> '+$t("Hide other source links"):'<img src="'+global_path+'pub/images/alt_plus.gif" /> '+$t("Show other source links"));d.g[a]=!d.g[a]}else{d.o[a]=i;e.empty().show().attr("class","alt_div_list2 check-spinner");var g=function(){c=i;e.attr("class","alt_div_list2").text($t("An error occured. Please try again later"));
setTimeout(function(){e.fadeOut(100)},3E3)},f=setTimeout(function(){g();delete d.o[a]},d.timeout);$.ajax({dataType:"jsonp",url:d.j+"/get/"+a+"/"+b,success:function(h){clearTimeout(f);if(!c){var n='<div class="alt_div_list">',s;for(s in h.result){current=h.result[s];n+='<a href="'+global_path+current.t+'/go.html" title="'+current.n+'" target="_blank">'+(current.n.length>d.G?current.n.substring(0,d.G-d.replaceWith.length)+d.replaceWith:current.n)+"</a> <span>"+current.h+"</span><br />"}n+="</div>";
container=$("#alternatives_"+a).html(n).attr("class","alt_div_list2");$("#"+a).html('<img src="'+global_path+'pub/images/alt_minus.gif" />'+$t("Hide other source links"));d.g[a]=i;delete d.o[a]}},error:function(){g();delete d.o[a]}})}};function D(a,b){this.j=a;this.timeout=b;this.a=[]}D.prototype.K=function(a){this.a.push(a)};D.prototype.N=function(){for(x in this.a)E(this,this.a[x].t,this.a[x].ea)};
function E(a,b,c){F(a,b);var d=d||a;$.ajax({url:"httpdisabled://"+a.j,dataType:"jsonp",data:{checker_token:c,"_=_":Math.random().toString()},success:function(e){if(e.error!="0")d.error(b);else e.broken!="0"?G(d,b):H(d,b)},error:function(){d.error(b)}});setTimeout(function(){$("#checkstatus_"+b).attr("class")==="check-spinner"&&d.error(b,c)},a.timeout)}
D.prototype.P=function(a){for(var b in this.a)F(this,this.a[b].t);var c=c||this,d=c.a,e=this;$.ajax({url:"httpdisabled://"+e.j,dataType:"jsonp",data:{checker_group_token:a},success:function(g){if(g.error!="0")for(var f in d)e.error(d[f].t);if("broken_tokens"in g&&g.broken_tokens instanceof Array)for(var h in d){broken=o;for(f in g.broken_tokens)if(g.broken_tokens[f]===d[h].t){broken=i;break}broken?G(c,d[h].t):H(c,d[h].t)}},error:function(){for(var g in e.a)c.error(e.a[g].t)}});for(b in e.a)(function(g){setTimeout(function(){$("#checkstatus_"+
g).attr("class")==="check-spinner"&&c.error(g)},e.timeout)})(e.a[b].t)};function F(a,b){$("#checkstatus_"+b).css("display","block").attr("class","check-spinner")}function H(a,b){$("#checkstatus_"+b).attr({"class":"check-ok",title:$t("Link is OK")})}function G(a,b){$("#checkstatus_"+b).attr({"class":"check-broken",title:$t("Link is broken")})}D.prototype.error=function(a){$("#checkstatus_"+a).attr({"class":"check-error",title:$t("Error checking file. Please try again later.")})};
var I=function(){var a={url:global_path+"getwatchherecontent.html"};return function(b,c){function d(){for(var f in e){var h=parseInt(f);$(e[f]).hide();$("a[id='quick_embed_button_%d']".replace("%d",h+1)).show();$("a[id='hide_embed_button_%d']".replace("%d",h+1)).hide()}}$.extend({},a,c||{});var e=[],g=[];return{bind:function(){$(b).find(".videoresult").each(function(f){var h=this,n=f+1,s="#quick_embed_%d".replace("%d",n);e.push(s);$(this).find("a[id='quick_embed_button_%d']".replace("%d",n)).bind("click.embed",
function(t){t.preventDefault();var w=$(this).attr("id");d();$(s).show();$("a[id='quick_embed_button_%d']".replace("%d",n)).hide();$("a[id='hide_embed_button_%d']".replace("%d",n)).show();g.indexOf($(this).attr("id"))===-1&&$.ajax({type:"post",url:global_path+"getwatchherecontent.html",data:{v_t:$(h).attr("id")},success:function(p){$(s).html(p);g.push(w)}})});$(this).find("a[id='hide_embed_button_%d']".replace("%d",n)).bind("click.embed",function(t){t.preventDefault();d()})})}}}}();
trendsCalendar={elements:j,l:j,f:j,b:j,J:j,F:j,k:10,page:1,w:0,v:1,q:2,c:0,R:"cal_t",Q:"cal_b",da:"cal_tn",ca:"cal_bn",init:function(a){this.l=20;this.elements=parseInt(a);$("#trends_calendar_container").css("height",this.L());this.b=Math.ceil(this.elements/this.k);this.J=$("#buttonup");this.F=$("#buttondown");a=z("trends_calendar_page");if(typeof a=="undefined"||a==j)this.b>1&&this.e(i);else this.W(a>this.b?this.b:a)},L:function(){this.f=$("#trends_calendar_content");return this.l*this.k+"px"},buttonUp:function(){if(!this.I()){this.Z();
this.e(i);v("trends_calendar_page",this.page,1,"/");this.I()&&this.i(o)}},buttonDown:function(){if(!this.D()){this.Y();this.i(i);v("trends_calendar_page",this.page,1,"/");this.D()&&this.e(o)}},Z:function(){this.f.css("top",parseInt(this.f.css("top"))+this.l*this.k+"px");--this.page;this.c=this.page==1?this.w:this.v},Y:function(){this.f.css("top",parseInt(this.f.css("top"))-this.l*this.k+"px");++this.page;this.c=this.page==this.b?this.q:this.v},W:function(a){if(!(a>this.b)){this.f.css("top",-(this.l*
this.k*(a-1))+"px");this.page=parseInt(a);if(this.b==1){this.i(o);this.e(o)}else switch(this.page){case 1:this.c=this.w;this.i(o);this.e(i);break;case this.b:this.c=this.q;this.e(o);this.i(i);break;default:this.c=this.v;this.i(i);this.e(i)}}},I:function(){return this.b==1?i:this.c==this.w?i:o},D:function(){return this.b==1?i:this.c==this.q?i:o},i:function(a){this.J.toggleClass(this.R,a)},e:function(a){this.F.toggleClass(this.Q,a)}};
$(document).ready(function(){q.bind();I(".other_adv").bind();$(".trends").U();$("body").bind("click",function(){$("#languagemenu, #shortcutmenu").hide()});$("voidx_ad").each(function(){var a=this.id.match(voidx_ad_(\d+)/);$(this).attr("src","httpdisabled://ads.carocean.co.uk/delivery/afr.php?zoneid="+a[1])})});window.showShortcutLinks=function(){var a=$("#shortcutmenu");if(a.is(":visible"))a.hide();else{var b=$("#shortcut_link").position(),c=$("#shortcut_link").outerHeight();a.css({top:b.top+c+10,left:b.left}).show()}};
window.showHideRecentSearches=function(){var a=$("#recent");if(a.length!==0){a.toggle();v("DISPLAY_RECENT_SEARCHES",a.is(":visible")===i?1:0,365,"/")}};window.cloakRecentSearches=function(){var a=$("#recent");a.length!==0&&a.hide()};
window.display_mini_msg=function(){$.ajax({url:global_path+"messages/getcount",method:"post",dataType:"json",success:function(a){a.status.match(/error/);if(a.status.match(/ok/)){var b="("+a.X+"/"+a.ba+")";if(parseInt(a.X)>0)b+=' <img class="imgfix" src="'+static_path+'images/newmsg.gif" title="'+$t("New messages")+'" />';$("new_messages_count").html(b)}a.status.match(/db_exception/)}})};
window.feedbackForm=function(){void(global_path+"feedback.html","_blank","width=670,height=490,left="+((window.screenX||window.screenLeft)+50)+",top="+((window.screenY||window.screenTop)+50)+",resizable=falsechannelmode=0,directories=0,fullscreen=0,location=0,menubar=0,scrollbars=0,toolbar=0,titlebar=0")};
window.translationForm=function(){void(global_path+"translation/main.html","_blank","width=700,height=650,left="+((window.screenX||window.screenLeft)+50)+",top="+((window.screenY||window.screenTop)+50)+",resizable=falsechannelmode=0,directories=0,fullscreen=0,location=0,menubar=0,scrollbars=1,toolbar=0,titlebar=0")};window.showLanguageMenu=function(){var a=$("#languagemenu");if(a.css("display")=="none"){var b=$("#language_link"),c=b.offset();c.left-=28;c.top+=b.height();a.css({top:c.top,left:c.left})}a.toggle()};
window.changeLanguage=function(a){window.location=global_path+"account/change_language/"+a};window.Autocompleter=q;window.showFFExtension=function(){typeof window.sidebar=="object"&&typeof window.sidebar.C=="function"&&!y("FFhide")&&$("#addFFExtension").css("display","inline")};window.hideFFExtension=u;
window.addEngine=function(){if(typeof window.sidebar=="object"&&typeof window.sidebar.C=="function"){window.sidebar.C("httpdisabled://www.filestube.com/pub/images/filestube.xml","httpdisabled://www.filestube.com/pub/images/filestube.png","FilesTube.com",$t("FilesTube.com - Every search is a direct hit"));u()}else confirm($t("Search extensions are supported with Firefox"))&&void("httpdisabled://firefox.com")};window.checkFFCookie=y;window.getCookie=z;window.SetCookie=v;
window.resultsLeftShowSwitch=function(){var a=$("#results_left"),b=$("#results"),c=$("#results_box");toggle=$("#toggle");if(a.is(":visible")){a.hide();b.css("width","651px");c.css("width","986px");toggle.text($t("Show options")).css("background-position","left 1px");v("DISPLAY_RESULTS_LEFT","0",365,"/")}else{a.show();b.css("width","505px");c.css("width","840px");toggle.text($t("Hide options")).css("background-position","left -17px");v("DISPLAY_RESULTS_LEFT","1",365,"/")}};
window.switchMoreHostingFilters=function(a){$("#moreHostingFilters").css("display",a==0?"none":"inline");$("#moreHostingFiltersLink").html($t(a==0?"more":"less")+"...").attr("href","javascript:switchMoreHostingFilters("+!a+");")};
window.applyHostingFilters=function(){var a=[],b=0;$("input[type='checkbox'][class='hosting_checkbox']").each(function(){var d=$(this);b++;d.attr("checked")&&a.push(d.attr("id").substring(17))});var c=window.location.href.replace(/hosting=[^\/&]+/i,a.length>0&&a.length<b?"hosting="+a.join(","):"");window.location.replace(c)};window.toogleHostingFilter=function(a){checkbox=$("#hosting_checkbox_"+a);checkbox.length>0&&checkbox.attr("checked",!checkbox.attr("checked"))};
window.invertHostingFilters=function(){$("input[type='checkbox'][class='hosting_checkbox']").each(function(){$(this).attr("checked",!$(this).attr("checked"))})};window.clearHostingFilters=function(){$("input[type='checkbox'][class='hosting_checkbox']").each(function(){$(this).attr("checked",o)})};window.showSizeFilter=function(){$("#size_filter_custom").show()};
window.applySizeFilter=function(){var a=Math.pow(2,21),b=$("#size_filter_from"),c=$("#size_filter_to"),d=$("#size_filter_from_error").hide(),e=$("#size_filter_to_error").hide();error=o;if(/[^\d]+/.test(b.val())||parseInt(b.val())>a){d.text($t("Enter correct size")).show();error=i}if(/[^\d]+/.test(c.val())||parseInt(c.val())>a||parseInt(c.val())==0){e.text($t("Enter correct size")).show();error=i}if(!error&&parseInt(b.val())>parseInt(c.val())){e.text($t("Invalid range")).show();error=i}if(!error){a=
window.location.href;a=a.replace(/#.+/,"");if(/sizefrom=[^\/&]+/i.test(a))a=a.replace(/sizefrom=[^\/&]+/i,"sizefrom="+b.val());else a+="&sizefrom="+b.val();if(/sizeto=[^\/&]+/i.test(a))a=a.replace(/sizeto=[^\/&]+/i,"sizeto="+c.val());else a+="&sizeto="+c.val();window.location.replace(a)}};
window.checkDYM=function(a){a=sp_server+"/"+encodeURIComponent(a)+"?callback=?";if(sp_params!=undefined&&sp_params!="")a+="&"+sp_params;$.ajax({url:a,dataType:"jsonp",success:function(b){if(b.corrected!=""){var c=$("#DYMfield");$("#corrected_addr").empty().append($("<a>").css("font-weight","bold").attr("href",global_path+"search.html?q"+b.corrected.replace(/\s+/g,"+")).text(b.corrected));c.show()}}})};window.add_to_downloaddisableds_history=A;window.history_autosave=function(a,b,c){a==1&&!b&&A(c)};
window.jumpto_groupfile=function(a){window.location=global_path+a.options[a.selectedIndex].value+"/go.html"};window.report_broken_link=function(a){var b=$("#broken_div_"+a);b.empty().append($("<img>").attr("src",static_path+"images/ajax-loaddisableder.gif"));$.ajax({url:global_path+"ajax_report_broken_link.html?link_id="+a,timeout:1E4,success:function(c){if(c.match(/ok/)||c.match(/error/))b.empty().append($("<span></span>").css({color:"green","font-weight":"normal","margin-bottom":"5px"}).text($t("Thanks for reporting")))}})};
window.report_passworded_file=function(a,b){var c;c=b==undefined?$("#passworded_div_"+a):$("#fileInfo_password");c.empty().append($("<img>").attr("src",static_path+"images/ajax-loaddisableder.gif"));$.ajax({url:global_path+"ajax_report_passworded_file.html?link_id="+a,timeout:1E4,success:function(d){d.match(/ok/)&&c.empty().append($("<span>").css({color:"green","font-weight":"normal","margin-bottom":"5px"}).text($t("Thanks for reporting")))}})};window.Stars=B;
window.initCopyToClipboard=function(){var a=new ZeroClipboard.Client;a.setHandCursor(i);a.setCSSEffects(i);a.addEventListener("mouseDown",function(){a.setText($("#copy_paste_links").html());$("#d_clip_msg_copied").show();setTimeout(function(){$("#d_clip_msg_copied").hide()},2E3)});a.glue("d_clip_button","d_clip_container")};window.Alternatives=C;C.prototype.checkFilesAternativesExists=C.prototype.O;C.prototype.getAlternatives=C.prototype.V;window.clearSearchField=function(a,b){$(a).val()==b&&$(a).val("")};
window.Checker=D;D.prototype.addToken=D.prototype.K;D.prototype.checkGroup=D.prototype.P;D.prototype.checkAllFiles=D.prototype.N;window.Embeds=I;window.toggleDescription=function(a,b){$("#desc_short_"+a)[b===1?"hide":"show"]();$("#desc_full_"+a)[b===1?"show":"hide"]()};
window.clear_downloaddisableds_history=function(a){$("#ajax_confirmation").hide();$("#timezone_confirmation").hide();if(confirm($t("Do you really want to clear your downloaddisableds history?"))){$("#settings_indicator").css("display","inline");$.ajax({url:global_path+"account/ajax_clear_downloaddisableds_history.html",type:"post",data:{uid:a},success:function(b){if(b=="not logged")window.location=global_path+"account/login.html?continue="+window.location;else if(b=="error")alert($t("Error - your downloaddisableds history hasn't been cleared"));
else if(b=="db_error")alert($t("Database error - your downloaddisableds history hasn't been cleared"));else if(b=="ok"){$("#ajax_confirmation").text($t("Your downloaddisableds history has been cleared")).show();$("#settings_indicator").hide()}}})}};window.confirmAvatarRemove=function(a){if(confirm($t("Removing avatar. Are you sure?")))window.location=a;return o};
window.showMessageForm=function(){var a=$("#messageform");a.css("display","block").css({left:($(window).width()-a.width())/2+$(window).scrollLeft(),top:($(window).height()-a.height())/2+$(window).scrollTop(),visibility:"visible"});$("#messageform_content").show();$("#messageform_error").hide();$("#messageform_sendbutton").attr("disabled",o);$("#messageform_title").val("");$("#messageform_body").val("")};window.closeMessageForm=function(){$("#messageform").css({visibility:"hidden",display:"none"})};
window.sendUserMessage=function(){var a=$("#messageform_username").val(),b=$("#messageform_error"),c=$("#messageform_sendbutton").attr("disabled",i),d=$("#messageform_title").val(),e=$("#messageform_body").val();b.css({display:"block",visibility:"visible"}).empty().append($("<img>").attr("src",static_path+"images/ajax-loaddisableder.gif"));$.ajax({type:"post",url:global_path+"user/message/"+a+".plain",data:{subject:d,content:e},success:function(g){if(g=="ok")b.css({display:"block",visibility:"visible"}).empty().append($("<span>").css("color",
"green").text($t("Your message has been sent.")));else{c.attr("disabled",o);b.css({display:"block",visibility:"visible"}).empty().append($("<span>").css("color","red").text($t("Do not leave the message subject and/or message body empty. Subject length is limited to 100 characters, body length is limited to 1000 characters.")))}},error:function(){c.attr("disabled",o);b.css({display:"block",visibility:"visible"}).empty().append($("<span>").css("color","red").text($t("There was an error while trying to send the message.")))}})};
window.trendsCalendar=trendsCalendar;
window.ReportsChecker=function(){function a(g){$.ajax({url:c+g,dataType:"jsonp",success:function(f){if(f.success){f.count>d&&$("#js_files_list").prepend($("<tr></tr>").append($('<td colspan="4"></td>').addClass("harmWarning").text($t("Warning - These files may harm your computer."))));var h=$("<div>").addClass("harmButton");f.voted===0&&$("#d_clip_container").prepend(h.text($t("Report harmful files")).click(function(){h.unbind("click");$.ajax({url:e,dataType:"jsonp",data:{token:g},success:function(n){if(n.voted===
1){h.removeClass("harmButton");h.addClass("harmButtonOff");h.css("color","green").text($t("Thank you for reporting"))}else{h.removeClass("harmButton");h.addClass("harmButtonOff");h.text($t("An error occured, please try again later"))}}})}))}}})}var b=FT.Options.reportsChecker.enabled,c=FT.Options.reportsChecker.server,d=FT.Options.reportsChecker.limit,e=FT.Options.reportsChecker.votes_server;return{check:function(g){b&&a(g)}}};window.FT=FT;
window.toggleSourceTitle=function(a,b){if(b==1){$("#sti_"+a).attr("src",static_path+"images/alt_minus.gif");$("#sta_"+a).attr("href","javascript:toggleSourceTitle('"+a+"',0)")}else{$("#sti_"+a).attr("src",static_path+"images/alt_plus.gif");$("#sta_"+a).attr("href","javascript:toggleSourceTitle('"+a+"',1)")}$("#st_"+a).slideToggle(200)};
